### ISSUE TITLE
resolver.doResolve() will not resolve main files when request points to a directory

### ISSUE THREAD

**Issue by brian-gonzalez** [webpack/enhanced-resolve#281]
With Webpack 5.x, when calling:

`resolver.doResolve(target, request, null, resolveContext, callback);`

Where `request.request` points to a directory instead of a file:
```
//This should be the same as '../path/to/directory/index.js'
'../path/to/directory'
```

The file is not resolved since the resolver does not look for `/index.js` anymore.

This was not a problem with Webpack 4.x, and interestingly enough Webpack itself doesn't seem to have a problem resolving these type of requests, the issue appears to only happen when building a custom resolver leveraging `enhanced-resolve`.

Is there any workaround for this? Any help is appreciated.

Thanks!

**Comment by alexander-akait** [comment]
Please create example how you run `resolver`

**Comment by brian-gonzalez** [comment]
@alexander-akait The plugin is used to provide an overlay/theme structure for JS, similar to how `includePaths` works in SCSS.

It takes an array of directories as a parameter, and it will attempt to resolve `import` calls based in the order provided by said array, looping it until it can find the file in the fallback system.


```
    apply(resolver) {
        const self = this;

        this.resolvedHook = resolver.ensureHook('parsed-resolve');
        this.resolver = resolver;

        this.resolver.getHook('before-resolve').tapAsync('RevolverPlugin', (requestContext, resolveContext, callback) => {
            //...

            directoryData = self.getDirectoryData(requestContext);
            //...
            self.walkDirectories({requestContext, resolveContext, directoryData, index}, callback);

            //...
        });
    }
```

**Comment by mjameswh** [comment]
@brian-gonzalez The structure of hooks in the resolve pipeline have change between Webpack 4 and Webpack 5.

`enhanced-resolve` still honour the `mainFiles` property, but the hook to which your plugin is connected is being called too early in the pipeline. I'm not so familiar with that pipeline either, so I don't know exactly what would be the tradeoffs / consequences of other specific hooks, but you should definitely try some later hooks rather than `"before-resolve"`.

Having a look at [this file](https://github.com/webpack/enhanced-resolve/blob/master/lib/ResolverFactory.js), I think you might have success if you hook on `"file"` or `"final-file"`...
