### ISSUE TITLE
Resolve main entry for bower and component

### ISSUE THREAD

**Issue by gunta** [webpack/enhanced-resolve#3]
Hi!

I would like to see support out of the box in webpack for not only **npm**, but also the other very popular package managers, **bower** and **component**.

I'm guessing it should be a matter of adding this:
```javascript
new DirectoryDescriptionFilePlugin("package.json", ["main"]),
new DirectoryDescriptionFilePlugin("bower.json", ["main"]),
new DirectoryDescriptionFilePlugin("component.json", ["main"]),
```

Thank you!

**Comment by sebastiandeutsch** [comment]
@akre54 I have the same problem. Do you have a solution yet?

**Comment by akre54** [comment]
We moved on from Chaplin, but as I recall there was a bug in
ContextRequirePlugin that sokra fixed pretty quickly. Try searching the
issues for my name.

**Comment by quarterto** [comment]
@gunta concatenating the files wouldn't always work. I've seen modules with main containing a JS file and a CSS file.

**Comment by gunta** [comment]
@quarterto that is still ok. You can have "sensible" values for the plugin as in:
```
if js 
    require js

if js + css
    require js
    require css
```

**Comment by quarterto** [comment]
What if you're not using Webpack for CSS?

**Comment by gunta** [comment]
@quarterto Well the idea is to optimise the workflow for the common case where you do use WebPack for all the assets.

Let's say you have the following library in a "widget-button" folder:
```
main:
  widget-button.js
  widget-button.css
```

Doing 
```
require('widget-button');
```
should require both files.

If you want to, for some reason, not use Webpack for the CSS, or not include any other assets,
you would do
```
require('widget-button/widget-button');
```

**Comment by cnlevy** [comment]
The current implementation for `new DirectoryDescriptionFilePlugin("bower.json", ["main"])`
doesn't work for bower.json description files when 'main' field is an array.

For example in the [angular-xeditable](https://github.com/vitalets/angular-xeditable/blob/master/bower.json) bower.json description file:
```
"main": [
    "dist/css/xeditable.css",
    "dist/js/xeditable.js"
  ],
```
[angular-growl-2](https://github.com/JanStevens/angular-growl-2/blob/master/bower.json)
```
"main": [
    "./build/angular-growl.js",
    "./build/angular-growl.css"
  ],
```
[angular-ui-bootstrap](https://github.com/angular-ui/bootstrap-bower/blob/master/bower.json)
`"main": ["./ui-bootstrap-tpls.js"],`

The expected behavior should be to require all files in the array, and return the .js file as module file

**Comment by sokra** [comment]
There is a bower-plugin, which should handle this

**Comment by linaspasv** [comment]
I have made a small plugin to support array like ``main`` fields in ``bower.json``: https://github.com/codewizz/bower-resolve-webpack-plugin
