### ISSUE TITLE
Backport preserve-symlinks fix to enhanced-resolve@0.9 for webpack@1

### ISSUE THREAD

**Issue by vjpr** [webpack/enhanced-resolve#45]
@sokra Could we get a backport to `enhanced-resolve@~0.9`?

`create-react-app` depends on `webpack@1.13.2` which depends on `enhanced-resolve@~0.9` and when installing with `pnpm` to a global symlinked store (the fastest way to install deps currently and what yarn may support eventually), it does not work.

**Comment by whitecolor** [comment]
Nasty problem.

**Comment by whitecolor** [comment]
I believe this is the solution:
https://webpack.js.org/configuration/resolve/#resolve-symlinks

**Comment by qiyuan-wang** [comment]
@whitecolor this solution won't work because it only deals with the first-level symlink.

When requiring a `symlink package` in inside a symlink package (like **[npminstall](https://github.com/cnpm/npminstall)** does, it installs all level dependencies in the form of symlink), it would throw a error of 'Module not found'.

I have a simple workaround for it: adding the root path to the config's `resolve.modules`. It works but slow down the building process.

We need a better way to solve this problem, an issue to `enhanced-resolve` maybe.

**Comment by whitecolor** [comment]
> We need a better way to solve this problem.

Don't use symlinks? 😄

**Comment by zkochan** [comment]
pnpm does not use the `--preserve-symlinks` flag anymore, so if webpack will use the same resolution algorithm that Node uses (which is resolving symlinks to real path), then it should work fine with pnpm.

> I believe this is the solution:
https://webpack.js.org/configuration/resolve/#resolve-symlinks

Maybe this could help with the issue described [here](https://github.com/webpack/webpack/issues/5087)?

**Comment by zkochan** [comment]
I just checked today and the latest pnpm works fine with the latest CRA. @vjpr could you recheck and confirm. In that case, I believe this can be closed

**Comment by vjpr** [comment]
Yeh this issue was only webpack@1 related.
