### ISSUE TITLE
Multiple modules support for alias

### ISSUE THREAD

**Issue by gunta** [webpack/enhanced-resolve#6]
Hi, currently I have the following alias configuration, which then I need to remember to include both files whenever I want to use the component:

``` javascript
alias: {
  'ng-file-upload-shim5': 'ng-file-upload/angular-file-upload-html5-shim',
  'ng-file-upload-main': 'ng-file-upload/angular-file-upload'
}
```

But would like to have only one entry for both files, like this:

``` javascript
alias: {
  'ng-file-upload': [
    'ng-file-upload/angular-file-upload-html5-shim',
    'ng-file-upload/angular-file-upload'
  ]
}
```

What do you think?

**Comment by amaschas** [comment]
Has there been any progress on this? I read the entire thread this issue was merged into, and it seems to relate to entirely separate issue. I'm having this same problem, and looking for a solution.

**Comment by mnpenner** [comment]
2nded. jQuery UI appears to have broke in v1.12 -- they split all the widgets into separate files and didn't provide a bundle so now I have no choice but to include them all separately. I'd like to make an alias that includes the whole lot of them so that I don't have to go around and fix all the things they broke.
